# Generated by Django 3.0.8 on 2020-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='bgColor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='footerColor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
