# Generated by Django 3.0.8 on 2020-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200723_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='quote',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
