# Generated by Django 3.0.8 on 2020-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200723_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='image',
            field=models.ImageField(upload_to='app/images/'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
